### ISSUE TITLE
Can't select dropdown menu in new GitHub UI

### ISSUE THREAD

**Issue by katabame** [synthtech/github-mod#14]
In new GitHub UI, dropdown menus are not active when hover, and can't click it.
![image](https://user-images.githubusercontent.com/9818101/40281115-2a4e56ca-5c98-11e8-9a9b-1a3cc8915337.png)

**Comment by h404bi** [comment]
Temporary workaround, remove:
``` css
    .dropdown-menu {
        z-index: 9;
    }
```
